version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gpvalise_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - gpvalise
    entrypoint: ["/bin/sh", "-c", "/var/www/docker/php/entrypoint.sh"]

  nginx:
    image: nginx:stable-alpine
    container_name: gpvalise_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gpvalise

  mysql:
    image: mysql:8.0
    container_name: gpvalise_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gpvalise
      MYSQL_USER: gpvalise_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gpvalise

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gpvalise_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: gpvalise_user
      PMA_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - gpvalise


volumes:
  db_data:

networks:
  gpvalise:
    driver: bridge
